openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
  termsOfService: 'https://example.com/terms/'
  contact:
    email: rishigarg185@gmail.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  # x-logo:
    # url: 'https://redocly.github.io/openapi-template/logo.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Users
    description: Operations about users.
  - name: Articles
    description: Operations about articles.
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  '/users':
    $ref: 'paths/create-user-request.yaml'
  '/users/{id}':
    $ref: 'paths/users.yaml'
  '/articles': 
    $ref: 'paths/create-article-request.yaml'
  '/articles/{id}':
    $ref: 'paths/articles.yaml'
